### ISSUE TITLE
Error in line 489

### ISSUE THREAD

**Issue by wolfram-dji** [anilyildizeldiven/childdeprivation#1]
**Error in line 489**

data11 <- replace_na_values(data10)

Error in `mutate()`:
! Can't transform a data frame with duplicate names.
Run `rlang::last_trace()` to see where the error occurred.

The code was running smoothly up until line 489. Do you have any idea what I or R might be doing wrong? I haven’t changed anything except the file paths to the raw data.

**Comment by anilyildizeldiven** [comment]
The basic reason for this is that in 'varlistpersons', which the code accesses to rename column names to German, some column names are duplicated. When renaming columns in the dataset, duplicate columns therefore also appear, as the error code indicates. The 'varlistpersons' list needs to be updated so that the code runs smoothly. I will do this as soon as possible

**Comment by anilyildizeldiven** [comment]
now it is updated
